version: '3.8'

services:
  web:
    build: .
    restart: always
    ports:
      - "8001:8000"
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
    deploy:
      resources:
        limits:
          cpus: "0.50"
          memory: "512M"
